# Generated by Django 4.1.7 on 2023-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='qno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
