# Generated by Django 4.1.7 on 2024-01-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0002_quest_qno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='optionA',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='optionB',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='optionC',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='optionD',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='entekt.quest')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entekt.option')),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='entekt.quest')),
            ],
        ),
    ]
