# Generated by Django 4.1.7 on 2024-01-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0003_remove_quest_answer_remove_quest_optiona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.AddField(
            model_name='option',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_letter',
            field=models.CharField(blank=True, max_length=1, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='correct_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entekt.option'),
        ),
    ]
