# Generated by Django 4.1.7 on 2024-01-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0004_remove_option_text_option_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
