# Generated by Django 4.1.7 on 2024-01-06 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0006_remove_correctanswer_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='correct_options',
            field=models.ManyToManyField(limit_choices_to={'question_id': django.db.models.expressions.OuterRef('quest_id')}, to='entekt.option'),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='quest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='entekt.quest'),
        ),
    ]
