# Generated by Django 4.1.7 on 2024-01-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0009_alter_correctanswer_correct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswer',
            name='correct_options',
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='correct_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_question', to='entekt.option'),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='entekt.quest'),
        ),
    ]
