# Generated by Django 4.1.7 on 2024-01-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0010_remove_correctanswer_correct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='correct_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_question', to='entekt.option'),
        ),
    ]
