# Generated by Django 4.1.7 on 2024-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0011_alter_correctanswer_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='correct_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
