# Generated by Django 4.1.7 on 2024-01-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entekt', '0012_alter_correctanswer_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='correct_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_question', to='entekt.option'),
        ),
    ]
